/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestorIndexRouteImport } from './routes/requestor/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as RequestorVendorsIndexRouteImport } from './routes/requestor/vendors/index'
import { Route as RequestorRequestsIndexRouteImport } from './routes/requestor/requests/index'
import { Route as RequestorVendorsIdRouteImport } from './routes/requestor/vendors/$id'
import { Route as RequestorRequestsCreateRouteImport } from './routes/requestor/requests/create'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestorIndexRoute = RequestorIndexRouteImport.update({
  id: '/requestor/',
  path: '/requestor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestorVendorsIndexRoute = RequestorVendorsIndexRouteImport.update({
  id: '/requestor/vendors/',
  path: '/requestor/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestorRequestsIndexRoute = RequestorRequestsIndexRouteImport.update({
  id: '/requestor/requests/',
  path: '/requestor/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestorVendorsIdRoute = RequestorVendorsIdRouteImport.update({
  id: '/requestor/vendors/$id',
  path: '/requestor/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestorRequestsCreateRoute = RequestorRequestsCreateRouteImport.update({
  id: '/requestor/requests/create',
  path: '/requestor/requests/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client': typeof ClientIndexRoute
  '/requestor': typeof RequestorIndexRoute
  '/requestor/requests/create': typeof RequestorRequestsCreateRoute
  '/requestor/vendors/$id': typeof RequestorVendorsIdRoute
  '/requestor/requests': typeof RequestorRequestsIndexRoute
  '/requestor/vendors': typeof RequestorVendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client': typeof ClientIndexRoute
  '/requestor': typeof RequestorIndexRoute
  '/requestor/requests/create': typeof RequestorRequestsCreateRoute
  '/requestor/vendors/$id': typeof RequestorVendorsIdRoute
  '/requestor/requests': typeof RequestorRequestsIndexRoute
  '/requestor/vendors': typeof RequestorVendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client/': typeof ClientIndexRoute
  '/requestor/': typeof RequestorIndexRoute
  '/requestor/requests/create': typeof RequestorRequestsCreateRoute
  '/requestor/vendors/$id': typeof RequestorVendorsIdRoute
  '/requestor/requests/': typeof RequestorRequestsIndexRoute
  '/requestor/vendors/': typeof RequestorVendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/client'
    | '/requestor'
    | '/requestor/requests/create'
    | '/requestor/vendors/$id'
    | '/requestor/requests'
    | '/requestor/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/client'
    | '/requestor'
    | '/requestor/requests/create'
    | '/requestor/vendors/$id'
    | '/requestor/requests'
    | '/requestor/vendors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/client/'
    | '/requestor/'
    | '/requestor/requests/create'
    | '/requestor/vendors/$id'
    | '/requestor/requests/'
    | '/requestor/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientIndexRoute: typeof ClientIndexRoute
  RequestorIndexRoute: typeof RequestorIndexRoute
  RequestorRequestsCreateRoute: typeof RequestorRequestsCreateRoute
  RequestorVendorsIdRoute: typeof RequestorVendorsIdRoute
  RequestorRequestsIndexRoute: typeof RequestorRequestsIndexRoute
  RequestorVendorsIndexRoute: typeof RequestorVendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requestor/': {
      id: '/requestor/'
      path: '/requestor'
      fullPath: '/requestor'
      preLoaderRoute: typeof RequestorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requestor/vendors/': {
      id: '/requestor/vendors/'
      path: '/requestor/vendors'
      fullPath: '/requestor/vendors'
      preLoaderRoute: typeof RequestorVendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requestor/requests/': {
      id: '/requestor/requests/'
      path: '/requestor/requests'
      fullPath: '/requestor/requests'
      preLoaderRoute: typeof RequestorRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requestor/vendors/$id': {
      id: '/requestor/vendors/$id'
      path: '/requestor/vendors/$id'
      fullPath: '/requestor/vendors/$id'
      preLoaderRoute: typeof RequestorVendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requestor/requests/create': {
      id: '/requestor/requests/create'
      path: '/requestor/requests/create'
      fullPath: '/requestor/requests/create'
      preLoaderRoute: typeof RequestorRequestsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientIndexRoute: ClientIndexRoute,
  RequestorIndexRoute: RequestorIndexRoute,
  RequestorRequestsCreateRoute: RequestorRequestsCreateRoute,
  RequestorVendorsIdRoute: RequestorVendorsIdRoute,
  RequestorRequestsIndexRoute: RequestorRequestsIndexRoute,
  RequestorVendorsIndexRoute: RequestorVendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
